### ISSUE TITLE
try_parse stuck in infinite loop

### ISSUE THREAD

**Issue by lucasavila00** [lomirus/html_editor#15]
The following HTML will cause try_parse to get stuck in an infinite loop

https://gist.github.com/lucasavila00/ae14f1b3284879add91f712663bdb4c7

`parse` does fail, with:

```
running 1 test
thread 'test_inf_loop' panicked at packages/rust-html2/src/lib.rs:494:37:
failed to parse: "<notranslate> is not closed"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::expect
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1034:23
   4: rust_webpack_template::transform_html_unbound
             at ./src/lib.rs:494:19
   5: rust_webpack_template::test_inf_loop
             at ./src/lib.rs:859:35
   6: rust_webpack_template::test_inf_loop::{{closure}}
             at ./src/lib.rs:852:20
   7: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test_inf_loop ... FAILED

```

**Comment by lucasavila00** [comment]
I ended up using html5ever as the fault tolerant parser, and converting the AST to html_editor:

```
use html5ever::tree_builder::TreeBuilderOpts;
use html5ever::{parse_document, Attribute, ParseOpts};
use html_editor::{operation::*, Element};
use html_editor::{parse, Node};
use rcdom::RcDom;
use serde::Serialize;
use wasm_bindgen::prelude::*;
extern crate markup5ever_rcdom as rcdom;
extern crate web_sys;
use html5ever::tendril::TendrilSink;

fn simplify_attributes(attrs: &Vec<Attribute>) -> Vec<(String, String)> {
    attrs
        .into_iter()
        .map(|it| (it.name.local.to_string(), it.value.to_string()))
        .collect()
}

fn simplify_html5ever_node(input: &rcdom::Node) -> Option<Node> {
    let children: Vec<Node> = input
        .children
        .borrow()
        .iter()
        .map(|it| simplify_html5ever_node(it))
        .flatten()
        .collect();

    match &input.data {
        rcdom::NodeData::Document => unreachable!("should be called before this"),
        rcdom::NodeData::Doctype {
            name: _,
            public_id: _,
            system_id: _,
        } => None,
        rcdom::NodeData::Text { contents } => Some(Node::Text(contents.borrow().to_string())),
        rcdom::NodeData::Comment { contents: _ } => None,
        rcdom::NodeData::Element {
            name,
            attrs,
            template_contents: _,
            mathml_annotation_xml_integration_point: _,
        } => Some(Node::Element(Element {
            name: name.local.to_string(),
            attrs: simplify_attributes(attrs.borrow().as_ref()),
            children,
        })),
        rcdom::NodeData::ProcessingInstruction {
            target: _,
            contents: _,
        } => None,
    }
}
fn simplify_html5ever(input: &rcdom::Node) -> Vec<Node> {
    if let rcdom::NodeData::Document = &input.data {
        input
            .children
            .borrow()
            .iter()
            .map(|it| simplify_html5ever_node(it))
            .flatten()
            .collect()
    } else {
        panic!("not a document")
    }
}
fn parse_html_with_html5ever(input_str: &str) -> Vec<Node> {
    let opts = ParseOpts {
        tree_builder: TreeBuilderOpts {
            drop_doctype: true,
            ..Default::default()
        },
        ..Default::default()
    };
    let mut bytes = input_str.as_bytes();
    let dom = parse_document(RcDom::default(), opts)
        .from_utf8()
        .read_from(&mut bytes)
        .unwrap();

    simplify_html5ever(dom.document.as_ref())
}
fn parse_html(input_str: &str) -> Vec<Node> {
    match parse(input_str) {
        Ok(n) => n,
        Err(_e) => parse_html_with_html5ever(input_str),
    }
}
```
